### ISSUE TITLE
PHP 7.1.12 nextcloud error

### ISSUE THREAD

**Issue by mwlczk** [hoellen/dockerfiles#1]
Following error is being logged: 
Narrowing  occurred during type inference. Please file a bug report on  bugs.php.net at /nextcloud/lib/composer/composer/ClassLoader.php#444

It is being investigated here: 
https://help.nextcloud.com/t/php-error-narrowing-occurred-during-type-inference/24010
and here:
https://bugs.php.net/bug.php?id=74980

we might need to downgrade the php version or just wait for backports for 7.2 compatibility from NC13

**Comment by hoellen** [comment]
I don't think they will release backports for 7.2 [nextcloud/server#7384](https://github.com/nextcloud/server/issues/7384). 
So I downgraded php to 7.1.11 and we will wait for a php fix.

**Comment by hoellen** [comment]
After the update to php 7.1.13 the bug should be fixed now.
