### ISSUE TITLE
Permission issue since last pull.

### ISSUE THREAD

**Issue by zerpex** [hoellen/dockerfiles#10]
Hi Hoellen,

Since the last image update, nextcloud is KO with the following error:
`An unhandled exception has been thrown:
Exception: Environment not properly prepared. in /nextcloud/lib/private/Console/Application.php:148
Stack trace:
#0 /nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /nextcloud/occ(11): require_once('/nextcloud/cons...')
s6-svscan: fatal: unable to mkfifo .s6-svscan/control: Permission denied
#2 {main}Skip checking permissions
Cannot write into "config" directory
This can usually be fixed by giving the webserver write access to the config directory. See https://docs.nextcloud.com/server/13/go.php?to=admin-dir_permissions`

Can you have a look ?

Regards,
z.

**Comment by mwalbeck** [comment]
Hi, I ran into the same problem. It seems it might be related to this commit 56507a1. It seems like it doesn't do the permissions check even though it should be the default behavior. Adding the environment variable CHECK_PERMISSIONS=1 to the docker container will fix it.

**Comment by hoellen** [comment]
Sorry, there was a typo which caused the wrong default behaviour. Fixed in 57230ff.

**Comment by zerpex** [comment]
You're right, there is a misspell on nextcloud/Dockerfile.13.0 : 
ChECK_PERMISSIONS=1

Need a "H" instead of "h".

I confirm that adding "CHECK_PERMISSIONS=1" on the docker-compose solves the problem.

Regards,
z.
