### ISSUE TITLE
Searx and nginx

### ISSUE THREAD

**Issue by masterzebra** [hoellen/dockerfiles#12]
Hi, im running yout searx dockerfile, works perfect

But im new with this and i have some questions to run a public instance

Searx dockerfile runs nginx, filtron or morty? Or just run searx?

If not, what nginx docker file do u suggest to run it? I see two

Thank u soo much

**Comment by hoellen** [comment]
Hey,

it just runs the searx webapp (python). To use it in production you can use [boring-nginx](
https://github.com/hoellen/dockerfiles/tree/master/boring-nginx) in front of it or any other reserve proxy. 

Greets 
hoellen

**Comment by masterzebra** [comment]
Hi, thank u soo much, i will try it
