### ISSUE TITLE
Download Abord with Big files

### ISSUE THREAD

**Issue by Moimemeici** [hoellen/dockerfiles#14]
Sorry for disturb.
But i have problem when i download big file.
After few minutes, download is abord.
Maybe problem configuration on my file.
Can you help me ?
Best regard
Sorry again for my english.

**Comment by hoellen** [comment]
Can you share your config file? If you're using nginx as reverse proxy, than you should set the following config option:
```
client_max_body_size 10G;
```

**Comment by Moimemeici** [comment]
This parameter, it's for upload no ?

> client_max_body_size 10G;

**Comment by Moimemeici** [comment]
the good parameter is 

`proxy_max_temp_file_size  100000M;`

work for me 
thx !

**Comment by hoellen** [comment]
Very good!
