### ISSUE TITLE
SOCKS5 Proxy does not work

### ISSUE THREAD

**Issue by DD8372812** [hoellen/dockerfiles#22]
Hello,

currently I'm testing your searx dockerfile. In my case I configured a Tor socks5 Proxy for outgoing connections as I did in wonderfalls dockerfile on 0.14.0 but it doesn't work. It seems searx ignores this setting. Is there semething to configure for prxy usage?

**Comment by hoellen** [comment]
I don't use searx in combination with tor, but it should be the same as wonderfalls image (since not many changes were made).
Is there something the log file? What contains `settings.yml` inside the container?

**Comment by DD8372812** [comment]
This is the setting of my yml regarding proxy:

```
proxies :
        http : socks5://192.168.1.150:9050
        https: socks5://192.168.1.150:9050
```
Currently I'm searching for searx logs but cannot find any. Do you know where they're written to?

**Comment by DD8372812** [comment]
When I look at:

> docker logs searx

I can't see anything interesting besides errors on search engines.

**Comment by hoellen** [comment]
Can't find anything about it. Maybe something broke with the update to 0.15 or your settings.yml has some other issues. Maybe I find some time next weekend for it. Or someone else knows what the problem is.

**Comment by DD8372812** [comment]
Hello hoellen,

thanks for help!
I installed your container 3 times yet. All installations have same problem. If I figure something out I'll let you know.

**Comment by hoellen** [comment]
@DD8372812 I just upgraded python to version 3 in the searx image. Can you please test, if the error still persists? Maybe it helped. Unfortunately I can't find anything else on my side.

**Comment by DD8372812** [comment]
@hoellen Thanks for that! I just tried to install it but get this error after container starts (it stops immediately):

```
1.2.2019 14:21:40Traceback (most recent call last):
1.2.2019 14:21:40  File "/usr/local/searx/searx/webapp.py", line 31, in <module>
1.2.2019 14:21:41    import requests
1.2.2019 14:21:41ModuleNotFoundError: No module named 'requests'
```

**Comment by hoellen** [comment]
Sorry, should work now.

**Comment by DD8372812** [comment]
Hm, still got the same error. Is it already published so I get the up to date version? Docker hub still says: "Updated 5 hours ago".
I have to leave my PC for some hours. Will test it tonight.
Thanks for your help!

**Comment by DD8372812** [comment]
Saw you updated it. Did have the time to test it quickly. But it seems to still ignore proxy settings. I am using same configuration in settings.yml as in wonderfall/searx container. So it should work. I can have a deeper look at it tonight.

By the way: what is the difference to wonderfalls searx container?

**Comment by hoellen** [comment]
Wonderfall discontinued the maintenance of his dockerfiles a while ago. Then I took care of it by myself. After some time he continued maintaining it again, but he can't take care of it very often (cause of limited time). So there are just little differences.

I saw that wonderfall updated his searx image also to 0.15. So now this images should be the same as this one. Did you tried the current version of wonderfall/searx image and there the proxy worked?

**Comment by DD8372812** [comment]
Hello hoellen,
thanks for answer.

Sorry, I was very busy this weekend. I just tried it again and it works. Did you change something after version on last Friday? Or was my quick test bad?

**Comment by hoellen** [comment]
I havn't changed anything since Friday. There was only the weekly rebuild. 
I'm glad it is working for you now.

**Comment by DD8372812** [comment]
Thanks again for your help :)
