### ISSUE TITLE
Does this automatically configure the database? transaction_isolation and binlog_format

### ISSUE THREAD

**Issue by mhbates** [hoellen/dockerfiles#23]
I'm assuming it does, but would just like to make sure. Thank you.

[mysqld]
...
transaction_isolation = READ-COMMITTED
binlog_format = ROW
...

**Comment by hoellen** [comment]
What exactly image do you mean? The images only starts the application and they usually create the corresponding database. 
If you want to change specific settings like isolation level, you usually have to do it yourself.

**Comment by mhbates** [comment]
Sorry, I'm referring to Nextcloud and the associated MariaDB docker setup you laid out. See this page: https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/linux_database_configuration.html

I'm guessing these settings should be added in the setup section for the db: https://github.com/hoellen/dockerfiles/tree/master/nextcloud

Like so:
```
docker run -d --name db_nextcloud \
       -v /docker/nextcloud/db:/var/lib/mysql \
       -e MYSQL_ROOT_PASSWORD=supersecretpassword \
       -e MYSQL_DATABASE=nextcloud -e MYSQL_USER=nextcloud \
       -e MYSQL_PASSWORD=supersecretpassword \
       mariadb:10 \
       --log-bin \
       --binlog-format=ROW \
       --transaction-isolation=READ-COMMITTED
```

**Comment by hoellen** [comment]
Since the db settings depends highly on your used database system and your hardware, I don't want to add these in general to the README.
I will put a reference to the Nextcloud documentation in the setup section.
