### ISSUE TITLE
Add argon2 

### ISSUE THREAD

**Issue by eloo** [hoellen/dockerfiles#30]
Hi,
would you mind to add argon2 support to your nginx-php image?
This will be used in nextcloud for password hashing.
If you want i can also provide a PR. (see https://github.com/Wonderfall/docker-nginx-php/pull/4)

Thanks

**Comment by hoellen** [comment]
Hello, 

I added argon2 support with cf3b8c5253b2052bf1554a62affb878e4ab021bf. The builds are already updated. Thanks for the hint.

With [PHP 7.4](https://wiki.php.net/rfc/sodium.argon.hash) there is no need for the additional dependencies (`argon2-dev` and `argon2-libs`). So maybe we should remove the package in near future again.

hoellen
