### ISSUE TITLE
not able to log in with reverse proxy

### ISSUE THREAD

**Issue by docfactory37** [hoellen/dockerfiles#32]
i have set up the nextcloud docker container and when im trying to access nextcloud form a reverse proxy i'm not able to i put in the correct username and password and it just reloads the login screen. but i'm able to login when using the ip address and port number.

**Comment by hoellen** [comment]
Can you share a little bit more about your setup? 
 - Nextcloud configuration?
 - What proxy server are you using?
 - Proxy server configuration?
 - What does the logs (proxy server, Nextcloud) say?
 - Network setup?
 - ...

**Comment by docfactory37** [comment]
Hi @hoellen,

I think it is working not i have had another look at the reverse proxy and look lik eit was an issue with Browers Cache, as i tried this on another devise and it was working. i will close this.
