### ISSUE TITLE
Error: "INotify file watcher" cannot be installed because the dependencies library inotify is not available.

### ISSUE THREAD

**Issue by skl283** [hoellen/dockerfiles#34]
Hi,

if i want to install the INotify File Watcher app, i get the following missing dependency error:

Exception: App "INotify file watcher" cannot be installed because the following dependencies are not fulfilled: The library inotify is not available.

Could you please add this library to get the App working?

thank you!

sash

**Comment by hoellen** [comment]
Hi @skl283,

sorry I don't want to add every dependency for every app. Maybe I will add this dependency at some point if more people request it, but not for now. A solution for you could be to add it simply by yourself.

Just create a `Dockerfile`. Something like that (not tested):
```
FROM hoellen/nextcloud:latest
RUN apk add inotify-tools
```

Then build the image with `docker build -t hoellen/nextcloud:latest`. Just run the build command to update your image.

If you have any further questions about this, please don't hesitate to ask.
hoellen
