### ISSUE TITLE
Correct PHP version to prevent log error warnings (access array offset)

### ISSUE THREAD

**Issue by rmeissn** [hoellen/dockerfiles#42]
I have a lot of "Trying to access array offset on value ..." in my Nextcloud logs, marked as level "Error". I searched Github a lot and and it seems to be some kind of Nextcloud ~bug when using PHP >7,2 (maybe only >7.3, not sure yet). See https://github.com/nextcloud/server/issues/19010#issuecomment-645163453

These "Trying to access array offset on value ..." are vary annoying as these messages spam the log file a lot. It seems to be some kind of upstream issue, that the developers won't fix in the near future - at least I interpreted their comments in this way.

It might be better to use PHP 7.2 oder 7.3 for your images, instead of 7.4, in order to get rid of these messages until a upstream fix is in place.

**Comment by hoellen** [comment]
Do the errors have negative effects? I would rather see the errors fixed upstream. The coming version Nextcloud 20 will require PHP 7.3+

**Comment by rmeissn** [comment]
Aside from quite large log files, that must be filtered from these kind of error messages, there are no negative effects.

**Comment by rmeissn** [comment]
The commit 5f65a6acc5297cf957396c8c77e0566162b2f4a9 fixes the excessive logging behaviour for NC 19
