### ISSUE TITLE
Add www-data user

### ISSUE THREAD

**Issue by eloo** [hoellen/dockerfiles#49]
Hi,

i'm curious if it makes sense to add the www-data(991) user to the image.
As this user (or better this id) is used for the permissions for the folders and also for the config.

What do you think?

Best regards
eloo

**Comment by hoellen** [comment]
Hello eloo,

it should be no problem, that the user doesn't exists in `/etc/passwd` as long as all of the numeric UIDs line up. On startup the process starts with the same UID as you data and config folder.

That makes it easier to change the UID by yourself with the environment variable (`UID=991`). No need to add the user in the startup script.

**As a note:** The upstream project from the Nextcloud Docker image ([Wonderfall/docker-nextcloud](https://github.com/Wonderfall/docker-nextcloud)) will update the image heavily, soon. I will adopt these changes to this image as well, for both security and maintenance reasons. With this change, permissions will work little differently (e.g. there will be no root process anymore, which changes the permissions on startup).

You can read more about it here: https://github.com/Wonderfall/docker-nextcloud/issues/80

Regards
hoellen

**Comment by eloo** [comment]
Hi,
okay.. then from my side we can close this issue. 

Thanks
