### ISSUE TITLE
Nextcloud: Download fails, if backend SMB is used.

### ISSUE THREAD

**Issue by waja** [hoellen/dockerfiles#50]
Seems this is triggered by https://github.com/nextcloud/server/issues/26457

**Comment by waja** [comment]
Replacing `/nextcloud/apps/files_external/3rdparty/icewind` from 21.0.0 release seems to fix the issue as workaround.

**Comment by waja** [comment]
Looks like https://github.com/icewind1991/SMB/pull/105 fixes the issue. If I'd know, how you prefer to include those changes (patches) into you Dockerfiles, I could prepare a PR.

**Comment by hoellen** [comment]
Thanks for the investigation. 
I would wait until the PR (https://github.com/nextcloud/server/pull/26627/) was merged and than add the patch to the Dockerfile.

**Comment by waja** [comment]
I prepared a PR at #51, just in case. :)

**Comment by hoellen** [comment]
Fixed with https://github.com/hoellen/dockerfiles/commit/ca8ae7b6b04faa751a40e5ea846c831b9f22fd85

**Comment by waja** [comment]
I can confirm, the problem is fixed. Thanks.
