### ISSUE TITLE
NextCloud Passwords App support only PHP8.0 -> update requested

### ISSUE THREAD

**Issue by GUNT0815** [hoellen/dockerfiles#59]
Based on the information here

https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/System-Requirements

the famous Passwords App in Nextcloud will only support php 8.0 from 2022 onward. The following hint appears for the application in Nextcloud:

"PHP 7.4.25 wird ab Version 2022.1.0 nicht mehr unterstützt. Bitte sieh dir unsere Systemanforderungen an."

In order to support the usage of the passwords app and allow a smooth transistion an update to php8.0 is requested.

**Comment by waja** [comment]
#61 brings php 8.0 and 8.1 images, which can be used as base image for nextcloud.

**Comment by hoellen** [comment]
For Nextcloud there is now a new [repository](https://github.com/hoellen/docker-nextcloud).
It is based on Wonderfalls "new" image and contains PHP 8 + Nextcloud 23.

The image works a bit different, so please have a look on the migration guide from Wonderfall: Wonderfall/docker-nextcloud#80
