### ISSUE TITLE
Rework build process to Github Actions

### ISSUE THREAD

**Issue by waja** [hoellen/dockerfiles#62]
As stated in https://github.com/hoellen/dockerfiles/pull/55#issuecomment-921829681, it would be nice to implement CI builds of the images via [Github Actions](https://github.com/features/actions).

While this is straight forward for repos with single purpose images, this is much more complicated when you maintain different tags (for example software versions) and even different purposes (multiple images in one repo, like nginx, nextcloud and so on).

@hoellen seems to be busy these days with other thinks, so it would be nice if some could draft an idea how this could be implemented or even better, draft a PR for this.

**Comment by waja** [comment]
Projects which can looked for inspirations I found with a quick search:

- https://github.com/vgist/dockerfiles
- https://github.com/stilleshan/dockerfiles
- https://github.com/HariSekhon/Dockerfiles
- https://github.com/oracle/docker-images
- https://github.com/tianon/dockerfiles

**Comment by hoellen** [comment]
Thank you for the suggestions, @waja. 
I started to adopt the Wonderfall changes. I will publish it in a dedicated repository soon. 
It will also use Github Actions.

**Comment by hoellen** [comment]
I pushed the repository to [hoellen/docker-nextcloud](https://github.com/hoellen/docker-nextcloud).
Please try and test the new image ([ghcr.io/hoellen/nextcloud](ghcr.io/hoellen/nextcloud)).
It is based on Wonderfalls "new" image and contains PHP 8 + Nextcloud 23.

The image works a bit different, so please use the migration guide from Wonderfall: https://github.com/Wonderfall/docker-nextcloud/issues/80
