### ISSUE TITLE
Nextcloud: latest image is not the latest

### ISSUE THREAD

**Issue by jazzdd86** [hoellen/dockerfiles#63]
The latest Docker Hub image for nextcloud is still 22.2.2 and not 22.2.3. It seems it did not get updated automatically as you did the changes in your Dockerfile. Could you please verify?

**Comment by waja** [comment]
please look info https://github.com/hoellen/dockerfiles/issues/62#issuecomment-986304118

**Comment by jazzdd86** [comment]
thx
