### ISSUE TITLE
not enough php-workers/servers/children

### ISSUE THREAD

**Issue by mwlczk** [hoellen/dockerfiles#7]
Hi,
when using the rainloop-plugin for webmail, nextcloud is stalling totaly because there is not enough php-processes to handle all the requests. 

> [pool www] server reached pm.max_children setting (15), consider raising it
and

> [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 32 children, there are 0 idle, and 8 total children

I set locally  those variables (php-fpm.conf) to a higher value and my nextcloud-instance is stable while using the rainloop-plugin. 
`
pm.max_children = 15 -> 50
pm.start_servers = 2->5
pm.min_spare_servers = 1->2
pm.max_spare_servers = 6->16
`

Of course other instances may not need that change or may not have that much ram and should stay with a lower value. So this should be controlled via an ENV-variable, or some other override mechanism.

What do You think about tweaking these values?

**Comment by hoellen** [comment]
I already thought about it to change these values. Personally I use a different `php-fpm.conf` with much higher values which is mounted via docker-compose in the volume section. 
I think it could be a problem in environments with low performance.

**Comment by zerpex** [comment]
+1 for controling these walues into env vars !

**Comment by hoellen** [comment]
There are now env variables for setting these values. It is documented in the [README](https://github.com/hoellen/dockerfiles/blob/master/nextcloud/README.md) file.
