### ISSUE TITLE
add option to set own nameserver

### ISSUE THREAD

**Issue by thiesmms** [hoellen/dockerfiles#8]
Hey there,

is it possible to add an ENV to manipulate the nameservers?
Or do I need to expose the resolv.conf and overwrite it manually?

thx

**Comment by hoellen** [comment]
I think Docker already provides an [option](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/) for this usecase. 

> 

> `--dns=IP_ADDRESS...` 
> Sets the IP addresses added as nameserver lines to the container's /etc/resolv.conf file. Processes in the container, when confronted with a hostname not in /etc/hosts, will connect to these IP addresses on port 53 looking for name resolution services.
>

**Comment by thiesmms** [comment]
that works thanks :)
